name: Workflow Debug

on:
  workflow_dispatch:

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        shell: bash
        run: env | sort

      - name: Step that fails
        shell: bash
        run: |
          echo "This step will fail"
          exit 1
