name: Workflow Debug

on:
  workflow_dispatch:

jobs:
  build:
    name: Debug Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug
        shell: bash
        run: env | sort

      - name: Execute on Debug
        shell: bash
        run: |
          echo "This is a debug step"
        if: ${{ env.RUNNER_DEBUG == '1' }}

      - name: Step that fails
        shell: bash
        run: |
          echo "This step will fail"
          exit 1
