name: Validate Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release version'
        required: true
        default: '1.0.0'

permissions:
  # This is required for report upload
  contents: write

jobs:
  create:
    name: Validate Release Items
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release Info
        run: gh release download "${{ inputs.releaseVersion }}" --pattern "release_id.txt"
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Read Maven Artifact ID
        id: get_run_id
        run: |
          echo "runId=$(cat release_id.txt)" >> $GITHUB_OUTPUT

      - name: Download Maven Artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_files
          run-id: ${{ steps.get_run_id.outputs.runId }}
          path: release_files

      - name: List Release Files
        run: |
          ls -al release_files/**
